on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .

    - name: Push Packages
      run: dotnet nuget push "*.${VERSION}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_PUBLISH} --skip-duplicate
      env:
        NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}
    
    - name: Push Symbol Packages
      run: dotnet nuget push "*.${VERSION}.snupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_PUBLISH} --skip-duplicate
      env:
        NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}